title:            吉小龙
description:      A jekyll theme. Because I scribble.
url:              http://jixiaolong.github.io:4000
signoff:          吉小龙
disqus_shortname: jixiaolonggithubio
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         关于我
    url:          /about
  - name:         博客
    url:          http://jixiaolong.github.io:4000
    external:     true
  - name:         联系我
    url:          mailto:jixiaolongcom@sina.cn
    external:     true
  - name:         GitHub
    url:          http://github.com/jixiaolong/
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
